### PR TITLE
Use sass-semver instead of micro-parser

### LINKED ISSUE #8: Externalize SemVer parsing
Hey, very nice library. I find the concept pretty cool and I admire the simplicity behind it. I can see how it would be useful for large projects moving fast (and trying not to break too many things).

I have been looking at the code and it’s stunning as always Kaelig, so I’ll make a single comment: I think the semver parsing and version comparison should not be part of sass-deprecate. The role of this library is to emit warnings and/or to remove code based on version numbers. Not to analyse and compare versions.

I would recommend you externalize the semver parsing and version comparison into another library, kind of like what npm does with https://github.com/npm/node-semver. Then, this library would be used as a dependency and expose a set of functions to compare versions, such as `gt($version-a, $version-b)` for instance. 

There are a few benefits in doing this: 

* It would remove about 80 lines of code from sass-deprecate if I’m right, which is basically dividing the amount of code per 2.
* It would make the semver parsing and version comparison more easily testable.
* It would make the semver parsing and version comparison re-usable in other projects needing it.
* It would be easy to replace this module with an actual node-semver binding through Sassport, or anything equivalent.
* Modular code is usually better.

Tell me if you want help with this.

### PR DESCRIPTION
**Pull request by HugoGiraudel**
Closes #8.

### CODE REVIEW

**Comment by kaelig** [comment]
Merci for the contribution.

After much consideration, it would probably make sense to keep a simple stripped down version that people can simply copy and paste. Not everyone uses npm in their stack and for this reason a tool like sass-deprecate should be agnostic.

How about adding the changes from this PR to a `index-full-semver-support.scss` (or similar) file that requires npm? This way, advanced users with a strong need for a full support of semver ranges could benefit from it.

Let me know if this makes sense, I'd love to hear your thoughts.

**Comment by HugoGiraudel** [comment]
Hey Kaelig,

To be honest I am not entirely sure. And the fact that I am not shows how terrible the Sass modules ecosystem really is. Packaging, distributing and using is not easy at all and it makes this kind of decisions much harder than they should be.

I think sass-deprecate could stay like this, as your micro-parser is very small and I believe that’s good. sass-semver is not that small since I tried to implement the node-semver API as well as possible. I’d say you don’t need all this.

What might be interesting on the other hand would be —if you want of course— adding a few sentences to the README explaining that sass-deprecate is pretty simple when it comes to semver and people are welcome to have a look at sass-semver if they needed it. 

Lastly, and because you were telling me the other day that you would like to have a single file so people can copy and paste freely, I have been thinking. This argument sounds like the same as “I want only one stylesheet in production so I have only one in development”. On sass-semver, I ended up having one function per file because it is much easier to maintain. Still, I have a simple npm script that bundles all these functions into `dist/index.scss`.

```
"scripts": {
  "build": "rm -rf dist/ && mkdir dist/ && cat src/* > dist/index.scss"
}
```

No dependency, no pipeline, none of that. Just a regular `cat` that dumps the whole thing into a single file so people can copy/paste it safely. You can also add this to the `prepublish` task:

```
"scripts": {
  "prepublish": "npm run build"
}
```

**Comment by kaelig** [comment]
How about using sass-Semver if available and fall back on the simpler version?

**Comment by HugoGiraudel** [comment]
Should work.

**Pull request closed without merging**
